// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/DiaElectronics/lea-central-wash/storageapi/model"
)

// AdvertisingCampaignByIDOKCode is the HTTP code returned for type AdvertisingCampaignByIDOK
const AdvertisingCampaignByIDOKCode int = 200

/*AdvertisingCampaignByIDOK OK

swagger:response advertisingCampaignByIdOK
*/
type AdvertisingCampaignByIDOK struct {

	/*
	  In: Body
	*/
	Payload *model.AdvertisingCampaign `json:"body,omitempty"`
}

// NewAdvertisingCampaignByIDOK creates AdvertisingCampaignByIDOK with default headers values
func NewAdvertisingCampaignByIDOK() *AdvertisingCampaignByIDOK {

	return &AdvertisingCampaignByIDOK{}
}

// WithPayload adds the payload to the advertising campaign by Id o k response
func (o *AdvertisingCampaignByIDOK) WithPayload(payload *model.AdvertisingCampaign) *AdvertisingCampaignByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the advertising campaign by Id o k response
func (o *AdvertisingCampaignByIDOK) SetPayload(payload *model.AdvertisingCampaign) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AdvertisingCampaignByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *AdvertisingCampaignByIDOK) AdvertisingCampaignByIDResponder() {}

// AdvertisingCampaignByIDUnauthorizedCode is the HTTP code returned for type AdvertisingCampaignByIDUnauthorized
const AdvertisingCampaignByIDUnauthorizedCode int = 401

/*AdvertisingCampaignByIDUnauthorized PIN is missing or invalid

swagger:response advertisingCampaignByIdUnauthorized
*/
type AdvertisingCampaignByIDUnauthorized struct {
}

// NewAdvertisingCampaignByIDUnauthorized creates AdvertisingCampaignByIDUnauthorized with default headers values
func NewAdvertisingCampaignByIDUnauthorized() *AdvertisingCampaignByIDUnauthorized {

	return &AdvertisingCampaignByIDUnauthorized{}
}

// WriteResponse to the client
func (o *AdvertisingCampaignByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

func (o *AdvertisingCampaignByIDUnauthorized) AdvertisingCampaignByIDResponder() {}

// AdvertisingCampaignByIDForbiddenCode is the HTTP code returned for type AdvertisingCampaignByIDForbidden
const AdvertisingCampaignByIDForbiddenCode int = 403

/*AdvertisingCampaignByIDForbidden Access forbiddenn

swagger:response advertisingCampaignByIdForbidden
*/
type AdvertisingCampaignByIDForbidden struct {
}

// NewAdvertisingCampaignByIDForbidden creates AdvertisingCampaignByIDForbidden with default headers values
func NewAdvertisingCampaignByIDForbidden() *AdvertisingCampaignByIDForbidden {

	return &AdvertisingCampaignByIDForbidden{}
}

// WriteResponse to the client
func (o *AdvertisingCampaignByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

func (o *AdvertisingCampaignByIDForbidden) AdvertisingCampaignByIDResponder() {}

// AdvertisingCampaignByIDInternalServerErrorCode is the HTTP code returned for type AdvertisingCampaignByIDInternalServerError
const AdvertisingCampaignByIDInternalServerErrorCode int = 500

/*AdvertisingCampaignByIDInternalServerError internal error

swagger:response advertisingCampaignByIdInternalServerError
*/
type AdvertisingCampaignByIDInternalServerError struct {
}

// NewAdvertisingCampaignByIDInternalServerError creates AdvertisingCampaignByIDInternalServerError with default headers values
func NewAdvertisingCampaignByIDInternalServerError() *AdvertisingCampaignByIDInternalServerError {

	return &AdvertisingCampaignByIDInternalServerError{}
}

// WriteResponse to the client
func (o *AdvertisingCampaignByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *AdvertisingCampaignByIDInternalServerError) AdvertisingCampaignByIDResponder() {}

type AdvertisingCampaignByIDNotImplementedResponder struct {
	middleware.Responder
}

func (*AdvertisingCampaignByIDNotImplementedResponder) AdvertisingCampaignByIDResponder() {}

func AdvertisingCampaignByIDNotImplemented() AdvertisingCampaignByIDResponder {
	return &AdvertisingCampaignByIDNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.AdvertisingCampaignByID has not yet been implemented",
		),
	}
}

type AdvertisingCampaignByIDResponder interface {
	middleware.Responder
	AdvertisingCampaignByIDResponder()
}
