// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/OpenRbt/lea-central-wash/storageapi/model"
)

// CreateTaskOKCode is the HTTP code returned for type CreateTaskOK
const CreateTaskOKCode int = 200

/*
CreateTaskOK OK

swagger:response createTaskOK
*/
type CreateTaskOK struct {

	/*
	  In: Body
	*/
	Payload *model.Task `json:"body,omitempty"`
}

// NewCreateTaskOK creates CreateTaskOK with default headers values
func NewCreateTaskOK() *CreateTaskOK {

	return &CreateTaskOK{}
}

// WithPayload adds the payload to the create task o k response
func (o *CreateTaskOK) WithPayload(payload *model.Task) *CreateTaskOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create task o k response
func (o *CreateTaskOK) SetPayload(payload *model.Task) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTaskOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *CreateTaskOK) CreateTaskResponder() {}

// CreateTaskBadRequestCode is the HTTP code returned for type CreateTaskBadRequest
const CreateTaskBadRequestCode int = 400

/*
CreateTaskBadRequest Bad Request

swagger:response createTaskBadRequest
*/
type CreateTaskBadRequest struct {
}

// NewCreateTaskBadRequest creates CreateTaskBadRequest with default headers values
func NewCreateTaskBadRequest() *CreateTaskBadRequest {

	return &CreateTaskBadRequest{}
}

// WriteResponse to the client
func (o *CreateTaskBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

func (o *CreateTaskBadRequest) CreateTaskResponder() {}

// CreateTaskUnauthorizedCode is the HTTP code returned for type CreateTaskUnauthorized
const CreateTaskUnauthorizedCode int = 401

/*
CreateTaskUnauthorized PIN is missing or invalid

swagger:response createTaskUnauthorized
*/
type CreateTaskUnauthorized struct {
}

// NewCreateTaskUnauthorized creates CreateTaskUnauthorized with default headers values
func NewCreateTaskUnauthorized() *CreateTaskUnauthorized {

	return &CreateTaskUnauthorized{}
}

// WriteResponse to the client
func (o *CreateTaskUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

func (o *CreateTaskUnauthorized) CreateTaskResponder() {}

// CreateTaskNotFoundCode is the HTTP code returned for type CreateTaskNotFound
const CreateTaskNotFoundCode int = 404

/*
CreateTaskNotFound Not found

swagger:response createTaskNotFound
*/
type CreateTaskNotFound struct {
}

// NewCreateTaskNotFound creates CreateTaskNotFound with default headers values
func NewCreateTaskNotFound() *CreateTaskNotFound {

	return &CreateTaskNotFound{}
}

// WriteResponse to the client
func (o *CreateTaskNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

func (o *CreateTaskNotFound) CreateTaskResponder() {}

// CreateTaskInternalServerErrorCode is the HTTP code returned for type CreateTaskInternalServerError
const CreateTaskInternalServerErrorCode int = 500

/*
CreateTaskInternalServerError Internal error

swagger:response createTaskInternalServerError
*/
type CreateTaskInternalServerError struct {
}

// NewCreateTaskInternalServerError creates CreateTaskInternalServerError with default headers values
func NewCreateTaskInternalServerError() *CreateTaskInternalServerError {

	return &CreateTaskInternalServerError{}
}

// WriteResponse to the client
func (o *CreateTaskInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *CreateTaskInternalServerError) CreateTaskResponder() {}

type CreateTaskNotImplementedResponder struct {
	middleware.Responder
}

func (*CreateTaskNotImplementedResponder) CreateTaskResponder() {}

func CreateTaskNotImplemented() CreateTaskResponder {
	return &CreateTaskNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.CreateTask has not yet been implemented",
		),
	}
}

type CreateTaskResponder interface {
	middleware.Responder
	CreateTaskResponder()
}
