// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// EditAdvertisingCampaignNoContentCode is the HTTP code returned for type EditAdvertisingCampaignNoContent
const EditAdvertisingCampaignNoContentCode int = 204

/*EditAdvertisingCampaignNoContent OK

swagger:response editAdvertisingCampaignNoContent
*/
type EditAdvertisingCampaignNoContent struct {
}

// NewEditAdvertisingCampaignNoContent creates EditAdvertisingCampaignNoContent with default headers values
func NewEditAdvertisingCampaignNoContent() *EditAdvertisingCampaignNoContent {

	return &EditAdvertisingCampaignNoContent{}
}

// WriteResponse to the client
func (o *EditAdvertisingCampaignNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *EditAdvertisingCampaignNoContent) EditAdvertisingCampaignResponder() {}

// EditAdvertisingCampaignUnauthorizedCode is the HTTP code returned for type EditAdvertisingCampaignUnauthorized
const EditAdvertisingCampaignUnauthorizedCode int = 401

/*EditAdvertisingCampaignUnauthorized PIN is missing or invalid

swagger:response editAdvertisingCampaignUnauthorized
*/
type EditAdvertisingCampaignUnauthorized struct {
}

// NewEditAdvertisingCampaignUnauthorized creates EditAdvertisingCampaignUnauthorized with default headers values
func NewEditAdvertisingCampaignUnauthorized() *EditAdvertisingCampaignUnauthorized {

	return &EditAdvertisingCampaignUnauthorized{}
}

// WriteResponse to the client
func (o *EditAdvertisingCampaignUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

func (o *EditAdvertisingCampaignUnauthorized) EditAdvertisingCampaignResponder() {}

// EditAdvertisingCampaignForbiddenCode is the HTTP code returned for type EditAdvertisingCampaignForbidden
const EditAdvertisingCampaignForbiddenCode int = 403

/*EditAdvertisingCampaignForbidden Access forbiddenn

swagger:response editAdvertisingCampaignForbidden
*/
type EditAdvertisingCampaignForbidden struct {
}

// NewEditAdvertisingCampaignForbidden creates EditAdvertisingCampaignForbidden with default headers values
func NewEditAdvertisingCampaignForbidden() *EditAdvertisingCampaignForbidden {

	return &EditAdvertisingCampaignForbidden{}
}

// WriteResponse to the client
func (o *EditAdvertisingCampaignForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

func (o *EditAdvertisingCampaignForbidden) EditAdvertisingCampaignResponder() {}

// EditAdvertisingCampaignInternalServerErrorCode is the HTTP code returned for type EditAdvertisingCampaignInternalServerError
const EditAdvertisingCampaignInternalServerErrorCode int = 500

/*EditAdvertisingCampaignInternalServerError internal error

swagger:response editAdvertisingCampaignInternalServerError
*/
type EditAdvertisingCampaignInternalServerError struct {
}

// NewEditAdvertisingCampaignInternalServerError creates EditAdvertisingCampaignInternalServerError with default headers values
func NewEditAdvertisingCampaignInternalServerError() *EditAdvertisingCampaignInternalServerError {

	return &EditAdvertisingCampaignInternalServerError{}
}

// WriteResponse to the client
func (o *EditAdvertisingCampaignInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *EditAdvertisingCampaignInternalServerError) EditAdvertisingCampaignResponder() {}

type EditAdvertisingCampaignNotImplementedResponder struct {
	middleware.Responder
}

func (*EditAdvertisingCampaignNotImplementedResponder) EditAdvertisingCampaignResponder() {}

func EditAdvertisingCampaignNotImplemented() EditAdvertisingCampaignResponder {
	return &EditAdvertisingCampaignNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.EditAdvertisingCampaign has not yet been implemented",
		),
	}
}

type EditAdvertisingCampaignResponder interface {
	middleware.Responder
	EditAdvertisingCampaignResponder()
}
