// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetListTasksParams creates a new GetListTasksParams object
//
// There are no default values defined in the spec.
func NewGetListTasksParams() GetListTasksParams {

	return GetListTasksParams{}
}

// GetListTasksParams contains all the bound params for the get list tasks operation
// typically these are obtained from a http.Request
//
// swagger:parameters getListTasks
type GetListTasksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Minimum: 1
	  In: query
	*/
	StationID *int64
	/*
	  In: query
	*/
	Status *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetListTasksParams() beforehand.
func (o *GetListTasksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qStationID, qhkStationID, _ := qs.GetOK("stationID")
	if err := o.bindStationID(qStationID, qhkStationID, route.Formats); err != nil {
		res = append(res, err)
	}

	qStatus, qhkStatus, _ := qs.GetOK("status")
	if err := o.bindStatus(qStatus, qhkStatus, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindStationID binds and validates parameter StationID from query.
func (o *GetListTasksParams) bindStationID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("stationID", "query", "int64", raw)
	}
	o.StationID = &value

	if err := o.validateStationID(formats); err != nil {
		return err
	}

	return nil
}

// validateStationID carries on validations for parameter StationID
func (o *GetListTasksParams) validateStationID(formats strfmt.Registry) error {

	if err := validate.MinimumInt("stationID", "query", *o.StationID, 1, false); err != nil {
		return err
	}

	return nil
}

// bindStatus binds and validates parameter Status from query.
func (o *GetListTasksParams) bindStatus(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Status = &raw

	if err := o.validateStatus(formats); err != nil {
		return err
	}

	return nil
}

// validateStatus carries on validations for parameter Status
func (o *GetListTasksParams) validateStatus(formats strfmt.Registry) error {

	if err := validate.EnumCase("status", "query", *o.Status, []interface{}{"queue", "started", "completed", "error"}, true); err != nil {
		return err
	}

	return nil
}
