// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/OpenRbt/lea-central-wash/storageapi/model"
)

// GetListTasksOKCode is the HTTP code returned for type GetListTasksOK
const GetListTasksOKCode int = 200

/*
GetListTasksOK OK

swagger:response getListTasksOK
*/
type GetListTasksOK struct {

	/*
	  In: Body
	*/
	Payload *model.TaskPage `json:"body,omitempty"`
}

// NewGetListTasksOK creates GetListTasksOK with default headers values
func NewGetListTasksOK() *GetListTasksOK {

	return &GetListTasksOK{}
}

// WithPayload adds the payload to the get list tasks o k response
func (o *GetListTasksOK) WithPayload(payload *model.TaskPage) *GetListTasksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get list tasks o k response
func (o *GetListTasksOK) SetPayload(payload *model.TaskPage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetListTasksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetListTasksOK) GetListTasksResponder() {}

// GetListTasksUnauthorizedCode is the HTTP code returned for type GetListTasksUnauthorized
const GetListTasksUnauthorizedCode int = 401

/*
GetListTasksUnauthorized PIN is missing or invalid

swagger:response getListTasksUnauthorized
*/
type GetListTasksUnauthorized struct {
}

// NewGetListTasksUnauthorized creates GetListTasksUnauthorized with default headers values
func NewGetListTasksUnauthorized() *GetListTasksUnauthorized {

	return &GetListTasksUnauthorized{}
}

// WriteResponse to the client
func (o *GetListTasksUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

func (o *GetListTasksUnauthorized) GetListTasksResponder() {}

// GetListTasksInternalServerErrorCode is the HTTP code returned for type GetListTasksInternalServerError
const GetListTasksInternalServerErrorCode int = 500

/*
GetListTasksInternalServerError Internal error

swagger:response getListTasksInternalServerError
*/
type GetListTasksInternalServerError struct {
}

// NewGetListTasksInternalServerError creates GetListTasksInternalServerError with default headers values
func NewGetListTasksInternalServerError() *GetListTasksInternalServerError {

	return &GetListTasksInternalServerError{}
}

// WriteResponse to the client
func (o *GetListTasksInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *GetListTasksInternalServerError) GetListTasksResponder() {}

type GetListTasksNotImplementedResponder struct {
	middleware.Responder
}

func (*GetListTasksNotImplementedResponder) GetListTasksResponder() {}

func GetListTasksNotImplemented() GetListTasksResponder {
	return &GetListTasksNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetListTasks has not yet been implemented",
		),
	}
}

type GetListTasksResponder interface {
	middleware.Responder
	GetListTasksResponder()
}
