// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/DiaElectronics/lea-central-wash/storageapi/model"
)

// GetLocalConfigVarIntOKCode is the HTTP code returned for type GetLocalConfigVarIntOK
const GetLocalConfigVarIntOKCode int = 200

/*
GetLocalConfigVarIntOK OK

swagger:response getLocalConfigVarIntOK
*/
type GetLocalConfigVarIntOK struct {

	/*
	  In: Body
	*/
	Payload *model.LocalConfigVarInt `json:"body,omitempty"`
}

// NewGetLocalConfigVarIntOK creates GetLocalConfigVarIntOK with default headers values
func NewGetLocalConfigVarIntOK() *GetLocalConfigVarIntOK {

	return &GetLocalConfigVarIntOK{}
}

// WithPayload adds the payload to the get local config var int o k response
func (o *GetLocalConfigVarIntOK) WithPayload(payload *model.LocalConfigVarInt) *GetLocalConfigVarIntOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get local config var int o k response
func (o *GetLocalConfigVarIntOK) SetPayload(payload *model.LocalConfigVarInt) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLocalConfigVarIntOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetLocalConfigVarIntOK) GetLocalConfigVarIntResponder() {}

// GetLocalConfigVarIntNotFoundCode is the HTTP code returned for type GetLocalConfigVarIntNotFound
const GetLocalConfigVarIntNotFoundCode int = 404

/*
GetLocalConfigVarIntNotFound Not found

swagger:response getLocalConfigVarIntNotFound
*/
type GetLocalConfigVarIntNotFound struct {
}

// NewGetLocalConfigVarIntNotFound creates GetLocalConfigVarIntNotFound with default headers values
func NewGetLocalConfigVarIntNotFound() *GetLocalConfigVarIntNotFound {

	return &GetLocalConfigVarIntNotFound{}
}

// WriteResponse to the client
func (o *GetLocalConfigVarIntNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

func (o *GetLocalConfigVarIntNotFound) GetLocalConfigVarIntResponder() {}

// GetLocalConfigVarIntInternalServerErrorCode is the HTTP code returned for type GetLocalConfigVarIntInternalServerError
const GetLocalConfigVarIntInternalServerErrorCode int = 500

/*
GetLocalConfigVarIntInternalServerError Internal error

swagger:response getLocalConfigVarIntInternalServerError
*/
type GetLocalConfigVarIntInternalServerError struct {
}

// NewGetLocalConfigVarIntInternalServerError creates GetLocalConfigVarIntInternalServerError with default headers values
func NewGetLocalConfigVarIntInternalServerError() *GetLocalConfigVarIntInternalServerError {

	return &GetLocalConfigVarIntInternalServerError{}
}

// WriteResponse to the client
func (o *GetLocalConfigVarIntInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *GetLocalConfigVarIntInternalServerError) GetLocalConfigVarIntResponder() {}

type GetLocalConfigVarIntNotImplementedResponder struct {
	middleware.Responder
}

func (*GetLocalConfigVarIntNotImplementedResponder) GetLocalConfigVarIntResponder() {}

func GetLocalConfigVarIntNotImplemented() GetLocalConfigVarIntResponder {
	return &GetLocalConfigVarIntNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetLocalConfigVarInt has not yet been implemented",
		),
	}
}

type GetLocalConfigVarIntResponder interface {
	middleware.Responder
	GetLocalConfigVarIntResponder()
}
