// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/DiaElectronics/lea-central-wash/storageapi/model"
	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// LoadMoneyHandlerFunc turns a function with the right signature into a load money handler
type LoadMoneyHandlerFunc func(LoadMoneyParams) LoadMoneyResponder

// Handle executing the request and returning a response
func (fn LoadMoneyHandlerFunc) Handle(params LoadMoneyParams) LoadMoneyResponder {
	return fn(params)
}

// LoadMoneyHandler interface for that can handle valid load money params
type LoadMoneyHandler interface {
	Handle(LoadMoneyParams) LoadMoneyResponder
}

// NewLoadMoney creates a new http.Handler for the load money operation
func NewLoadMoney(ctx *middleware.Context, handler LoadMoneyHandler) *LoadMoney {
	return &LoadMoney{Context: ctx, Handler: handler}
}

/*LoadMoney swagger:route POST /load-money loadMoney

LoadMoney load money API

*/
type LoadMoney struct {
	Context *middleware.Context
	Handler LoadMoneyHandler
}

func (o *LoadMoney) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLoadMoneyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// LoadMoneyBody load money body
// swagger:model LoadMoneyBody
type LoadMoneyBody struct {

	// hash
	// Required: true
	Hash model.Hash `json:"hash"`
}

// Validate validates this load money body
func (o *LoadMoneyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateHash(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *LoadMoneyBody) validateHash(formats strfmt.Registry) error {

	if err := o.Hash.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "hash")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *LoadMoneyBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LoadMoneyBody) UnmarshalBinary(b []byte) error {
	var res LoadMoneyBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
