// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"
)

// ProgramsHandlerFunc turns a function with the right signature into a programs handler
type ProgramsHandlerFunc func(ProgramsParams) ProgramsResponder

// Handle executing the request and returning a response
func (fn ProgramsHandlerFunc) Handle(params ProgramsParams) ProgramsResponder {
	return fn(params)
}

// ProgramsHandler interface for that can handle valid programs params
type ProgramsHandler interface {
	Handle(ProgramsParams) ProgramsResponder
}

// NewPrograms creates a new http.Handler for the programs operation
func NewPrograms(ctx *middleware.Context, handler ProgramsHandler) *Programs {
	return &Programs{Context: ctx, Handler: handler}
}

/*Programs swagger:route POST /programs programs

Programs programs API

*/
type Programs struct {
	Context *middleware.Context
	Handler ProgramsHandler
}

func (o *Programs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewProgramsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ProgramsBody programs body
// swagger:model ProgramsBody
type ProgramsBody struct {

	// station ID
	// Required: true
	// Minimum: 1
	StationID *int64 `json:"stationID"`
}

// Validate validates this programs body
func (o *ProgramsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateStationID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ProgramsBody) validateStationID(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"stationID", "body", o.StationID); err != nil {
		return err
	}

	if err := validate.MinimumInt("args"+"."+"stationID", "body", int64(*o.StationID), 1, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ProgramsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ProgramsBody) UnmarshalBinary(b []byte) error {
	var res ProgramsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
