// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// ProgramStopNoContentCode is the HTTP code returned for type ProgramStopNoContent
const ProgramStopNoContentCode int = 204

/*
ProgramStopNoContent OK

swagger:response programStopNoContent
*/
type ProgramStopNoContent struct {
}

// NewProgramStopNoContent creates ProgramStopNoContent with default headers values
func NewProgramStopNoContent() *ProgramStopNoContent {

	return &ProgramStopNoContent{}
}

// WriteResponse to the client
func (o *ProgramStopNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *ProgramStopNoContent) ProgramStopResponder() {}

// ProgramStopNotFoundCode is the HTTP code returned for type ProgramStopNotFound
const ProgramStopNotFoundCode int = 404

/*
ProgramStopNotFound not found

swagger:response programStopNotFound
*/
type ProgramStopNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewProgramStopNotFound creates ProgramStopNotFound with default headers values
func NewProgramStopNotFound() *ProgramStopNotFound {

	return &ProgramStopNotFound{}
}

// WithPayload adds the payload to the program stop not found response
func (o *ProgramStopNotFound) WithPayload(payload string) *ProgramStopNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the program stop not found response
func (o *ProgramStopNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProgramStopNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *ProgramStopNotFound) ProgramStopResponder() {}

// ProgramStopInternalServerErrorCode is the HTTP code returned for type ProgramStopInternalServerError
const ProgramStopInternalServerErrorCode int = 500

/*
ProgramStopInternalServerError internal error

swagger:response programStopInternalServerError
*/
type ProgramStopInternalServerError struct {
}

// NewProgramStopInternalServerError creates ProgramStopInternalServerError with default headers values
func NewProgramStopInternalServerError() *ProgramStopInternalServerError {

	return &ProgramStopInternalServerError{}
}

// WriteResponse to the client
func (o *ProgramStopInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *ProgramStopInternalServerError) ProgramStopResponder() {}

type ProgramStopNotImplementedResponder struct {
	middleware.Responder
}

func (*ProgramStopNotImplementedResponder) ProgramStopResponder() {}

func ProgramStopNotImplemented() ProgramStopResponder {
	return &ProgramStopNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.ProgramStop has not yet been implemented",
		),
	}
}

type ProgramStopResponder interface {
	middleware.Responder
	ProgramStopResponder()
}
