// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// ResetStationStatNoContentCode is the HTTP code returned for type ResetStationStatNoContent
const ResetStationStatNoContentCode int = 204

/*
ResetStationStatNoContent OK

swagger:response resetStationStatNoContent
*/
type ResetStationStatNoContent struct {
}

// NewResetStationStatNoContent creates ResetStationStatNoContent with default headers values
func NewResetStationStatNoContent() *ResetStationStatNoContent {

	return &ResetStationStatNoContent{}
}

// WriteResponse to the client
func (o *ResetStationStatNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *ResetStationStatNoContent) ResetStationStatResponder() {}

// ResetStationStatUnauthorizedCode is the HTTP code returned for type ResetStationStatUnauthorized
const ResetStationStatUnauthorizedCode int = 401

/*
ResetStationStatUnauthorized PIN is missing or invalid

swagger:response resetStationStatUnauthorized
*/
type ResetStationStatUnauthorized struct {
}

// NewResetStationStatUnauthorized creates ResetStationStatUnauthorized with default headers values
func NewResetStationStatUnauthorized() *ResetStationStatUnauthorized {

	return &ResetStationStatUnauthorized{}
}

// WriteResponse to the client
func (o *ResetStationStatUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

func (o *ResetStationStatUnauthorized) ResetStationStatResponder() {}

// ResetStationStatForbiddenCode is the HTTP code returned for type ResetStationStatForbidden
const ResetStationStatForbiddenCode int = 403

/*
ResetStationStatForbidden Access forbidden

swagger:response resetStationStatForbidden
*/
type ResetStationStatForbidden struct {
}

// NewResetStationStatForbidden creates ResetStationStatForbidden with default headers values
func NewResetStationStatForbidden() *ResetStationStatForbidden {

	return &ResetStationStatForbidden{}
}

// WriteResponse to the client
func (o *ResetStationStatForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

func (o *ResetStationStatForbidden) ResetStationStatResponder() {}

// ResetStationStatInternalServerErrorCode is the HTTP code returned for type ResetStationStatInternalServerError
const ResetStationStatInternalServerErrorCode int = 500

/*
ResetStationStatInternalServerError internal error

swagger:response resetStationStatInternalServerError
*/
type ResetStationStatInternalServerError struct {
}

// NewResetStationStatInternalServerError creates ResetStationStatInternalServerError with default headers values
func NewResetStationStatInternalServerError() *ResetStationStatInternalServerError {

	return &ResetStationStatInternalServerError{}
}

// WriteResponse to the client
func (o *ResetStationStatInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *ResetStationStatInternalServerError) ResetStationStatResponder() {}

type ResetStationStatNotImplementedResponder struct {
	middleware.Responder
}

func (*ResetStationStatNotImplementedResponder) ResetStationStatResponder() {}

func ResetStationStatNotImplemented() ResetStationStatResponder {
	return &ResetStationStatNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.ResetStationStat has not yet been implemented",
		),
	}
}

type ResetStationStatResponder interface {
	middleware.Responder
	ResetStationStatResponder()
}
