// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
)

// SaveNoContentCode is the HTTP code returned for type SaveNoContent
const SaveNoContentCode int = 204

/*SaveNoContent OK

swagger:response saveNoContent
*/
type SaveNoContent struct {
}

// NewSaveNoContent creates SaveNoContent with default headers values
func NewSaveNoContent() *SaveNoContent {

	return &SaveNoContent{}
}

// WriteResponse to the client
func (o *SaveNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *SaveNoContent) SaveResponder() {}

// SaveNotFoundCode is the HTTP code returned for type SaveNotFound
const SaveNotFoundCode int = 404

/*SaveNotFound not found

swagger:response saveNotFound
*/
type SaveNotFound struct {
}

// NewSaveNotFound creates SaveNotFound with default headers values
func NewSaveNotFound() *SaveNotFound {

	return &SaveNotFound{}
}

// WriteResponse to the client
func (o *SaveNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

func (o *SaveNotFound) SaveResponder() {}

// SaveInternalServerErrorCode is the HTTP code returned for type SaveInternalServerError
const SaveInternalServerErrorCode int = 500

/*SaveInternalServerError internal error

swagger:response saveInternalServerError
*/
type SaveInternalServerError struct {
}

// NewSaveInternalServerError creates SaveInternalServerError with default headers values
func NewSaveInternalServerError() *SaveInternalServerError {

	return &SaveInternalServerError{}
}

// WriteResponse to the client
func (o *SaveInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *SaveInternalServerError) SaveResponder() {}

type SaveNotImplementedResponder struct {
	middleware.Responder
}

func (*SaveNotImplementedResponder) SaveResponder() {}

func SaveNotImplemented() SaveResponder {
	return &SaveNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.Save has not yet been implemented",
		),
	}
}

type SaveResponder interface {
	middleware.Responder
	SaveResponder()
}
