// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/DiaElectronics/lea-central-wash/storageapi/model"
)

// StatusCollectionOKCode is the HTTP code returned for type StatusCollectionOK
const StatusCollectionOKCode int = 200

/*
StatusCollectionOK OK

swagger:response statusCollectionOK
*/
type StatusCollectionOK struct {

	/*
	  In: Body
	*/
	Payload *model.StatusCollectionReport `json:"body,omitempty"`
}

// NewStatusCollectionOK creates StatusCollectionOK with default headers values
func NewStatusCollectionOK() *StatusCollectionOK {

	return &StatusCollectionOK{}
}

// WithPayload adds the payload to the status collection o k response
func (o *StatusCollectionOK) WithPayload(payload *model.StatusCollectionReport) *StatusCollectionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status collection o k response
func (o *StatusCollectionOK) SetPayload(payload *model.StatusCollectionReport) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StatusCollectionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *StatusCollectionOK) StatusCollectionResponder() {}

// StatusCollectionUnauthorizedCode is the HTTP code returned for type StatusCollectionUnauthorized
const StatusCollectionUnauthorizedCode int = 401

/*
StatusCollectionUnauthorized PIN is missing or invalid

swagger:response statusCollectionUnauthorized
*/
type StatusCollectionUnauthorized struct {
}

// NewStatusCollectionUnauthorized creates StatusCollectionUnauthorized with default headers values
func NewStatusCollectionUnauthorized() *StatusCollectionUnauthorized {

	return &StatusCollectionUnauthorized{}
}

// WriteResponse to the client
func (o *StatusCollectionUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

func (o *StatusCollectionUnauthorized) StatusCollectionResponder() {}

// StatusCollectionForbiddenCode is the HTTP code returned for type StatusCollectionForbidden
const StatusCollectionForbiddenCode int = 403

/*
StatusCollectionForbidden Access forbidden

swagger:response statusCollectionForbidden
*/
type StatusCollectionForbidden struct {
}

// NewStatusCollectionForbidden creates StatusCollectionForbidden with default headers values
func NewStatusCollectionForbidden() *StatusCollectionForbidden {

	return &StatusCollectionForbidden{}
}

// WriteResponse to the client
func (o *StatusCollectionForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

func (o *StatusCollectionForbidden) StatusCollectionResponder() {}

// StatusCollectionInternalServerErrorCode is the HTTP code returned for type StatusCollectionInternalServerError
const StatusCollectionInternalServerErrorCode int = 500

/*
StatusCollectionInternalServerError internal error

swagger:response statusCollectionInternalServerError
*/
type StatusCollectionInternalServerError struct {
}

// NewStatusCollectionInternalServerError creates StatusCollectionInternalServerError with default headers values
func NewStatusCollectionInternalServerError() *StatusCollectionInternalServerError {

	return &StatusCollectionInternalServerError{}
}

// WriteResponse to the client
func (o *StatusCollectionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *StatusCollectionInternalServerError) StatusCollectionResponder() {}

type StatusCollectionNotImplementedResponder struct {
	middleware.Responder
}

func (*StatusCollectionNotImplementedResponder) StatusCollectionResponder() {}

func StatusCollectionNotImplemented() StatusCollectionResponder {
	return &StatusCollectionNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.StatusCollection has not yet been implemented",
		),
	}
}

type StatusCollectionResponder interface {
	middleware.Responder
	StatusCollectionResponder()
}
