// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
)

// StationByHashOKCode is the HTTP code returned for type StationByHashOK
const StationByHashOKCode int = 200

/*StationByHashOK OK

swagger:response stationByHashOK
*/
type StationByHashOK struct {

	/*
	  In: Body
	*/
	Payload int64 `json:"body,omitempty"`
}

// NewStationByHashOK creates StationByHashOK with default headers values
func NewStationByHashOK() *StationByHashOK {

	return &StationByHashOK{}
}

// WithPayload adds the payload to the station by hash o k response
func (o *StationByHashOK) WithPayload(payload int64) *StationByHashOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the station by hash o k response
func (o *StationByHashOK) SetPayload(payload int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StationByHashOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *StationByHashOK) StationByHashResponder() {}

// StationByHashInternalServerErrorCode is the HTTP code returned for type StationByHashInternalServerError
const StationByHashInternalServerErrorCode int = 500

/*StationByHashInternalServerError internal error

swagger:response stationByHashInternalServerError
*/
type StationByHashInternalServerError struct {
}

// NewStationByHashInternalServerError creates StationByHashInternalServerError with default headers values
func NewStationByHashInternalServerError() *StationByHashInternalServerError {

	return &StationByHashInternalServerError{}
}

// WriteResponse to the client
func (o *StationByHashInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

func (o *StationByHashInternalServerError) StationByHashResponder() {}

type StationByHashNotImplementedResponder struct {
	middleware.Responder
}

func (*StationByHashNotImplementedResponder) StationByHashResponder() {}

func StationByHashNotImplemented() StationByHashResponder {
	return &StationByHashNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.StationByHash has not yet been implemented",
		),
	}
}

type StationByHashResponder interface {
	middleware.Responder
	StationByHashResponder()
}
