// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Storage",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/info": {
      "get": {
        "operationId": "info",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/load": {
      "post": {
        "operationId": "load",
        "parameters": [
          {
            "name": "args",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "hash",
                "key"
              ],
              "properties": {
                "hash": {
                  "$ref": "#/definitions/Hash"
                },
                "key": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "not found"
          },
          "500": {
            "description": "internal error"
          }
        }
      }
    },
    "/ping": {
      "post": {
        "operationId": "ping",
        "parameters": [
          {
            "name": "args",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "hash"
              ],
              "properties": {
                "hash": {
                  "$ref": "#/definitions/Hash"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "serviceAmount"
              ],
              "properties": {
                "serviceAmount": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    },
    "/save": {
      "post": {
        "operationId": "save",
        "parameters": [
          {
            "name": "args",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "hash",
                "keyPair"
              ],
              "properties": {
                "hash": {
                  "$ref": "#/definitions/Hash"
                },
                "keyPair": {
                  "$ref": "#/definitions/KeyPair"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "OK"
          },
          "500": {
            "description": "internal error"
          }
        }
      }
    }
  },
  "definitions": {
    "Hash": {
      "type": "string",
      "minLength": 1
    },
    "KeyPair": {
      "type": "object",
      "required": [
        "key",
        "value"
      ],
      "properties": {
        "key": {
          "type": "string",
          "minLength": 1
        },
        "value": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Storage",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/info": {
      "get": {
        "operationId": "info",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/load": {
      "post": {
        "operationId": "load",
        "parameters": [
          {
            "name": "args",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "hash",
                "key"
              ],
              "properties": {
                "hash": {
                  "$ref": "#/definitions/Hash"
                },
                "key": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "not found"
          },
          "500": {
            "description": "internal error"
          }
        }
      }
    },
    "/ping": {
      "post": {
        "operationId": "ping",
        "parameters": [
          {
            "name": "args",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "hash"
              ],
              "properties": {
                "hash": {
                  "$ref": "#/definitions/Hash"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "serviceAmount"
              ],
              "properties": {
                "serviceAmount": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    },
    "/save": {
      "post": {
        "operationId": "save",
        "parameters": [
          {
            "name": "args",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "hash",
                "keyPair"
              ],
              "properties": {
                "hash": {
                  "$ref": "#/definitions/Hash"
                },
                "keyPair": {
                  "$ref": "#/definitions/KeyPair"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "OK"
          },
          "500": {
            "description": "internal error"
          }
        }
      }
    }
  },
  "definitions": {
    "Hash": {
      "type": "string",
      "minLength": 1
    },
    "KeyPair": {
      "type": "object",
      "required": [
        "key",
        "value"
      ],
      "properties": {
        "key": {
          "type": "string",
          "minLength": 1
        },
        "value": {
          "type": "string"
        }
      }
    }
  }
}`))
}
