// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateTaskByHash create task by hash
//
// swagger:model CreateTaskByHash
type CreateTaskByHash struct {

	// hash
	// Required: true
	Hash *string `json:"hash"`

	// type
	// Required: true
	// Enum: [build update reboot getVersions pullFirmware setVersion]
	Type *string `json:"type"`

	// version ID
	VersionID *int64 `json:"versionID,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *CreateTaskByHash) UnmarshalJSON(data []byte) error {
	var props struct {

		// hash
		// Required: true
		Hash *string `json:"hash"`

		// type
		// Required: true
		// Enum: [build update reboot getVersions pullFirmware setVersion]
		Type *string `json:"type"`

		// version ID
		VersionID *int64 `json:"versionID,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Hash = props.Hash
	m.Type = props.Type
	m.VersionID = props.VersionID
	return nil
}

// Validate validates this create task by hash
func (m *CreateTaskByHash) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHash(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateTaskByHash) validateHash(formats strfmt.Registry) error {

	if err := validate.Required("hash", "body", m.Hash); err != nil {
		return err
	}

	return nil
}

var createTaskByHashTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["build","update","reboot","getVersions","pullFirmware","setVersion"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createTaskByHashTypeTypePropEnum = append(createTaskByHashTypeTypePropEnum, v)
	}
}

const (

	// CreateTaskByHashTypeBuild captures enum value "build"
	CreateTaskByHashTypeBuild string = "build"

	// CreateTaskByHashTypeUpdate captures enum value "update"
	CreateTaskByHashTypeUpdate string = "update"

	// CreateTaskByHashTypeReboot captures enum value "reboot"
	CreateTaskByHashTypeReboot string = "reboot"

	// CreateTaskByHashTypeGetVersions captures enum value "getVersions"
	CreateTaskByHashTypeGetVersions string = "getVersions"

	// CreateTaskByHashTypePullFirmware captures enum value "pullFirmware"
	CreateTaskByHashTypePullFirmware string = "pullFirmware"

	// CreateTaskByHashTypeSetVersion captures enum value "setVersion"
	CreateTaskByHashTypeSetVersion string = "setVersion"
)

// prop value enum
func (m *CreateTaskByHash) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createTaskByHashTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateTaskByHash) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create task by hash based on context it is used
func (m *CreateTaskByHash) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateTaskByHash) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateTaskByHash) UnmarshalBinary(b []byte) error {
	var res CreateTaskByHash
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
