// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IsOperator is operator
//
// swagger:model IsOperator
type IsOperator bool

// Validate validates this is operator
func (m IsOperator) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this is operator based on context it is used
func (m IsOperator) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
