// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StationsVariables stations variables
//
// swagger:model StationsVariables
type StationsVariables struct {

	// hash
	Hash *string `json:"hash,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// key pairs
	KeyPairs []*KeyPair `json:"keyPairs"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this stations variables
func (m *StationsVariables) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeyPairs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StationsVariables) validateKeyPairs(formats strfmt.Registry) error {
	if swag.IsZero(m.KeyPairs) { // not required
		return nil
	}

	for i := 0; i < len(m.KeyPairs); i++ {
		if swag.IsZero(m.KeyPairs[i]) { // not required
			continue
		}

		if m.KeyPairs[i] != nil {
			if err := m.KeyPairs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("keyPairs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this stations variables based on the context it is used
func (m *StationsVariables) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateKeyPairs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StationsVariables) contextValidateKeyPairs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.KeyPairs); i++ {

		if m.KeyPairs[i] != nil {
			if err := m.KeyPairs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("keyPairs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *StationsVariables) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StationsVariables) UnmarshalBinary(b []byte) error {
	var res StationsVariables
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
