// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/OpenRbt/lea-central-wash/storageapi/model"
)

// NewAddLogParams creates a new AddLogParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddLogParams() *AddLogParams {
	return &AddLogParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddLogParamsWithTimeout creates a new AddLogParams object
// with the ability to set a timeout on a request.
func NewAddLogParamsWithTimeout(timeout time.Duration) *AddLogParams {
	return &AddLogParams{
		timeout: timeout,
	}
}

// NewAddLogParamsWithContext creates a new AddLogParams object
// with the ability to set a context for a request.
func NewAddLogParamsWithContext(ctx context.Context) *AddLogParams {
	return &AddLogParams{
		Context: ctx,
	}
}

// NewAddLogParamsWithHTTPClient creates a new AddLogParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddLogParamsWithHTTPClient(client *http.Client) *AddLogParams {
	return &AddLogParams{
		HTTPClient: client,
	}
}

/*
AddLogParams contains all the parameters to send to the API endpoint

	for the add log operation.

	Typically these are written to a http.Request.
*/
type AddLogParams struct {

	// Args.
	Args *model.Log

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add log params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddLogParams) WithDefaults() *AddLogParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add log params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddLogParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add log params
func (o *AddLogParams) WithTimeout(timeout time.Duration) *AddLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add log params
func (o *AddLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add log params
func (o *AddLogParams) WithContext(ctx context.Context) *AddLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add log params
func (o *AddLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add log params
func (o *AddLogParams) WithHTTPClient(client *http.Client) *AddLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add log params
func (o *AddLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the add log params
func (o *AddLogParams) WithArgs(args *model.Log) *AddLogParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the add log params
func (o *AddLogParams) SetArgs(args *model.Log) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *AddLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Args != nil {
		if err := r.SetBodyParam(o.Args); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
