// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/DiaElectronics/lea-central-wash/storageapi/model"
)

// AdvertisingCampaignByIDReader is a Reader for the AdvertisingCampaignByID structure.
type AdvertisingCampaignByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AdvertisingCampaignByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAdvertisingCampaignByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAdvertisingCampaignByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAdvertisingCampaignByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAdvertisingCampaignByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAdvertisingCampaignByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAdvertisingCampaignByIDOK creates a AdvertisingCampaignByIDOK with default headers values
func NewAdvertisingCampaignByIDOK() *AdvertisingCampaignByIDOK {
	return &AdvertisingCampaignByIDOK{}
}

/*
AdvertisingCampaignByIDOK describes a response with status code 200, with default header values.

OK
*/
type AdvertisingCampaignByIDOK struct {
	Payload *model.AdvertisingCampaign
}

// IsSuccess returns true when this advertising campaign by Id o k response has a 2xx status code
func (o *AdvertisingCampaignByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this advertising campaign by Id o k response has a 3xx status code
func (o *AdvertisingCampaignByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this advertising campaign by Id o k response has a 4xx status code
func (o *AdvertisingCampaignByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this advertising campaign by Id o k response has a 5xx status code
func (o *AdvertisingCampaignByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this advertising campaign by Id o k response a status code equal to that given
func (o *AdvertisingCampaignByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the advertising campaign by Id o k response
func (o *AdvertisingCampaignByIDOK) Code() int {
	return 200
}

func (o *AdvertisingCampaignByIDOK) Error() string {
	return fmt.Sprintf("[POST /advertising-campaign-by-id][%d] advertisingCampaignByIdOK  %+v", 200, o.Payload)
}

func (o *AdvertisingCampaignByIDOK) String() string {
	return fmt.Sprintf("[POST /advertising-campaign-by-id][%d] advertisingCampaignByIdOK  %+v", 200, o.Payload)
}

func (o *AdvertisingCampaignByIDOK) GetPayload() *model.AdvertisingCampaign {
	return o.Payload
}

func (o *AdvertisingCampaignByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.AdvertisingCampaign)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAdvertisingCampaignByIDUnauthorized creates a AdvertisingCampaignByIDUnauthorized with default headers values
func NewAdvertisingCampaignByIDUnauthorized() *AdvertisingCampaignByIDUnauthorized {
	return &AdvertisingCampaignByIDUnauthorized{}
}

/*
AdvertisingCampaignByIDUnauthorized describes a response with status code 401, with default header values.

PIN is missing or invalid
*/
type AdvertisingCampaignByIDUnauthorized struct {
}

// IsSuccess returns true when this advertising campaign by Id unauthorized response has a 2xx status code
func (o *AdvertisingCampaignByIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this advertising campaign by Id unauthorized response has a 3xx status code
func (o *AdvertisingCampaignByIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this advertising campaign by Id unauthorized response has a 4xx status code
func (o *AdvertisingCampaignByIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this advertising campaign by Id unauthorized response has a 5xx status code
func (o *AdvertisingCampaignByIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this advertising campaign by Id unauthorized response a status code equal to that given
func (o *AdvertisingCampaignByIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the advertising campaign by Id unauthorized response
func (o *AdvertisingCampaignByIDUnauthorized) Code() int {
	return 401
}

func (o *AdvertisingCampaignByIDUnauthorized) Error() string {
	return fmt.Sprintf("[POST /advertising-campaign-by-id][%d] advertisingCampaignByIdUnauthorized ", 401)
}

func (o *AdvertisingCampaignByIDUnauthorized) String() string {
	return fmt.Sprintf("[POST /advertising-campaign-by-id][%d] advertisingCampaignByIdUnauthorized ", 401)
}

func (o *AdvertisingCampaignByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAdvertisingCampaignByIDForbidden creates a AdvertisingCampaignByIDForbidden with default headers values
func NewAdvertisingCampaignByIDForbidden() *AdvertisingCampaignByIDForbidden {
	return &AdvertisingCampaignByIDForbidden{}
}

/*
AdvertisingCampaignByIDForbidden describes a response with status code 403, with default header values.

Access forbidden
*/
type AdvertisingCampaignByIDForbidden struct {
}

// IsSuccess returns true when this advertising campaign by Id forbidden response has a 2xx status code
func (o *AdvertisingCampaignByIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this advertising campaign by Id forbidden response has a 3xx status code
func (o *AdvertisingCampaignByIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this advertising campaign by Id forbidden response has a 4xx status code
func (o *AdvertisingCampaignByIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this advertising campaign by Id forbidden response has a 5xx status code
func (o *AdvertisingCampaignByIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this advertising campaign by Id forbidden response a status code equal to that given
func (o *AdvertisingCampaignByIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the advertising campaign by Id forbidden response
func (o *AdvertisingCampaignByIDForbidden) Code() int {
	return 403
}

func (o *AdvertisingCampaignByIDForbidden) Error() string {
	return fmt.Sprintf("[POST /advertising-campaign-by-id][%d] advertisingCampaignByIdForbidden ", 403)
}

func (o *AdvertisingCampaignByIDForbidden) String() string {
	return fmt.Sprintf("[POST /advertising-campaign-by-id][%d] advertisingCampaignByIdForbidden ", 403)
}

func (o *AdvertisingCampaignByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAdvertisingCampaignByIDNotFound creates a AdvertisingCampaignByIDNotFound with default headers values
func NewAdvertisingCampaignByIDNotFound() *AdvertisingCampaignByIDNotFound {
	return &AdvertisingCampaignByIDNotFound{}
}

/*
AdvertisingCampaignByIDNotFound describes a response with status code 404, with default header values.

not found
*/
type AdvertisingCampaignByIDNotFound struct {
}

// IsSuccess returns true when this advertising campaign by Id not found response has a 2xx status code
func (o *AdvertisingCampaignByIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this advertising campaign by Id not found response has a 3xx status code
func (o *AdvertisingCampaignByIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this advertising campaign by Id not found response has a 4xx status code
func (o *AdvertisingCampaignByIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this advertising campaign by Id not found response has a 5xx status code
func (o *AdvertisingCampaignByIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this advertising campaign by Id not found response a status code equal to that given
func (o *AdvertisingCampaignByIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the advertising campaign by Id not found response
func (o *AdvertisingCampaignByIDNotFound) Code() int {
	return 404
}

func (o *AdvertisingCampaignByIDNotFound) Error() string {
	return fmt.Sprintf("[POST /advertising-campaign-by-id][%d] advertisingCampaignByIdNotFound ", 404)
}

func (o *AdvertisingCampaignByIDNotFound) String() string {
	return fmt.Sprintf("[POST /advertising-campaign-by-id][%d] advertisingCampaignByIdNotFound ", 404)
}

func (o *AdvertisingCampaignByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAdvertisingCampaignByIDInternalServerError creates a AdvertisingCampaignByIDInternalServerError with default headers values
func NewAdvertisingCampaignByIDInternalServerError() *AdvertisingCampaignByIDInternalServerError {
	return &AdvertisingCampaignByIDInternalServerError{}
}

/*
AdvertisingCampaignByIDInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type AdvertisingCampaignByIDInternalServerError struct {
}

// IsSuccess returns true when this advertising campaign by Id internal server error response has a 2xx status code
func (o *AdvertisingCampaignByIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this advertising campaign by Id internal server error response has a 3xx status code
func (o *AdvertisingCampaignByIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this advertising campaign by Id internal server error response has a 4xx status code
func (o *AdvertisingCampaignByIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this advertising campaign by Id internal server error response has a 5xx status code
func (o *AdvertisingCampaignByIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this advertising campaign by Id internal server error response a status code equal to that given
func (o *AdvertisingCampaignByIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the advertising campaign by Id internal server error response
func (o *AdvertisingCampaignByIDInternalServerError) Code() int {
	return 500
}

func (o *AdvertisingCampaignByIDInternalServerError) Error() string {
	return fmt.Sprintf("[POST /advertising-campaign-by-id][%d] advertisingCampaignByIdInternalServerError ", 500)
}

func (o *AdvertisingCampaignByIDInternalServerError) String() string {
	return fmt.Sprintf("[POST /advertising-campaign-by-id][%d] advertisingCampaignByIdInternalServerError ", 500)
}

func (o *AdvertisingCampaignByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
AdvertisingCampaignByIDBody ArgAdvertisingCampaignByID
swagger:model AdvertisingCampaignByIDBody
*/
type AdvertisingCampaignByIDBody struct {

	// id
	// Required: true
	ID *int64 `json:"id"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (o *AdvertisingCampaignByIDBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// id
		// Required: true
		ID *int64 `json:"id"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	o.ID = props.ID
	return nil
}

// Validate validates this advertising campaign by ID body
func (o *AdvertisingCampaignByIDBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AdvertisingCampaignByIDBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this advertising campaign by ID body based on context it is used
func (o *AdvertisingCampaignByIDBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AdvertisingCampaignByIDBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AdvertisingCampaignByIDBody) UnmarshalBinary(b []byte) error {
	var res AdvertisingCampaignByIDBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
