// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EditAdvertisingCampaignReader is a Reader for the EditAdvertisingCampaign structure.
type EditAdvertisingCampaignReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EditAdvertisingCampaignReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewEditAdvertisingCampaignNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewEditAdvertisingCampaignUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewEditAdvertisingCampaignForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEditAdvertisingCampaignInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEditAdvertisingCampaignNoContent creates a EditAdvertisingCampaignNoContent with default headers values
func NewEditAdvertisingCampaignNoContent() *EditAdvertisingCampaignNoContent {
	return &EditAdvertisingCampaignNoContent{}
}

/* EditAdvertisingCampaignNoContent describes a response with status code 204, with default header values.

OK
*/
type EditAdvertisingCampaignNoContent struct {
}

func (o *EditAdvertisingCampaignNoContent) Error() string {
	return fmt.Sprintf("[POST /edit-advertising-campaign][%d] editAdvertisingCampaignNoContent ", 204)
}

func (o *EditAdvertisingCampaignNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEditAdvertisingCampaignUnauthorized creates a EditAdvertisingCampaignUnauthorized with default headers values
func NewEditAdvertisingCampaignUnauthorized() *EditAdvertisingCampaignUnauthorized {
	return &EditAdvertisingCampaignUnauthorized{}
}

/* EditAdvertisingCampaignUnauthorized describes a response with status code 401, with default header values.

PIN is missing or invalid
*/
type EditAdvertisingCampaignUnauthorized struct {
}

func (o *EditAdvertisingCampaignUnauthorized) Error() string {
	return fmt.Sprintf("[POST /edit-advertising-campaign][%d] editAdvertisingCampaignUnauthorized ", 401)
}

func (o *EditAdvertisingCampaignUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEditAdvertisingCampaignForbidden creates a EditAdvertisingCampaignForbidden with default headers values
func NewEditAdvertisingCampaignForbidden() *EditAdvertisingCampaignForbidden {
	return &EditAdvertisingCampaignForbidden{}
}

/* EditAdvertisingCampaignForbidden describes a response with status code 403, with default header values.

Access forbiddenn
*/
type EditAdvertisingCampaignForbidden struct {
}

func (o *EditAdvertisingCampaignForbidden) Error() string {
	return fmt.Sprintf("[POST /edit-advertising-campaign][%d] editAdvertisingCampaignForbidden ", 403)
}

func (o *EditAdvertisingCampaignForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEditAdvertisingCampaignInternalServerError creates a EditAdvertisingCampaignInternalServerError with default headers values
func NewEditAdvertisingCampaignInternalServerError() *EditAdvertisingCampaignInternalServerError {
	return &EditAdvertisingCampaignInternalServerError{}
}

/* EditAdvertisingCampaignInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type EditAdvertisingCampaignInternalServerError struct {
}

func (o *EditAdvertisingCampaignInternalServerError) Error() string {
	return fmt.Sprintf("[POST /edit-advertising-campaign][%d] editAdvertisingCampaignInternalServerError ", 500)
}

func (o *EditAdvertisingCampaignInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
