// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLoadRelayParams creates a new LoadRelayParams object
// with the default values initialized.
func NewLoadRelayParams() *LoadRelayParams {
	var ()
	return &LoadRelayParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoadRelayParamsWithTimeout creates a new LoadRelayParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoadRelayParamsWithTimeout(timeout time.Duration) *LoadRelayParams {
	var ()
	return &LoadRelayParams{

		timeout: timeout,
	}
}

// NewLoadRelayParamsWithContext creates a new LoadRelayParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoadRelayParamsWithContext(ctx context.Context) *LoadRelayParams {
	var ()
	return &LoadRelayParams{

		Context: ctx,
	}
}

// NewLoadRelayParamsWithHTTPClient creates a new LoadRelayParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLoadRelayParamsWithHTTPClient(client *http.Client) *LoadRelayParams {
	var ()
	return &LoadRelayParams{
		HTTPClient: client,
	}
}

/*LoadRelayParams contains all the parameters to send to the API endpoint
for the load relay operation typically these are written to a http.Request
*/
type LoadRelayParams struct {

	/*Args*/
	Args LoadRelayBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the load relay params
func (o *LoadRelayParams) WithTimeout(timeout time.Duration) *LoadRelayParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the load relay params
func (o *LoadRelayParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the load relay params
func (o *LoadRelayParams) WithContext(ctx context.Context) *LoadRelayParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the load relay params
func (o *LoadRelayParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the load relay params
func (o *LoadRelayParams) WithHTTPClient(client *http.Client) *LoadRelayParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the load relay params
func (o *LoadRelayParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the load relay params
func (o *LoadRelayParams) WithArgs(args LoadRelayBody) *LoadRelayParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the load relay params
func (o *LoadRelayParams) SetArgs(args LoadRelayBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *LoadRelayParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
