// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/DiaElectronics/lea-central-wash/storageapi/model"
)

// PressButtonReader is a Reader for the PressButton structure.
type PressButtonReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PressButtonReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPressButtonNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewPressButtonNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPressButtonInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPressButtonNoContent creates a PressButtonNoContent with default headers values
func NewPressButtonNoContent() *PressButtonNoContent {
	return &PressButtonNoContent{}
}

/*PressButtonNoContent handles this case with default header values.

OK
*/
type PressButtonNoContent struct {
}

func (o *PressButtonNoContent) Error() string {
	return fmt.Sprintf("[POST /press-button][%d] pressButtonNoContent ", 204)
}

func (o *PressButtonNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPressButtonNotFound creates a PressButtonNotFound with default headers values
func NewPressButtonNotFound() *PressButtonNotFound {
	return &PressButtonNotFound{}
}

/*PressButtonNotFound handles this case with default header values.

not found
*/
type PressButtonNotFound struct {
	Payload string
}

func (o *PressButtonNotFound) Error() string {
	return fmt.Sprintf("[POST /press-button][%d] pressButtonNotFound  %+v", 404, o.Payload)
}

func (o *PressButtonNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPressButtonInternalServerError creates a PressButtonInternalServerError with default headers values
func NewPressButtonInternalServerError() *PressButtonInternalServerError {
	return &PressButtonInternalServerError{}
}

/*PressButtonInternalServerError handles this case with default header values.

internal error
*/
type PressButtonInternalServerError struct {
}

func (o *PressButtonInternalServerError) Error() string {
	return fmt.Sprintf("[POST /press-button][%d] pressButtonInternalServerError ", 500)
}

func (o *PressButtonInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PressButtonBody press button body
swagger:model PressButtonBody
*/
type PressButtonBody struct {

	// button ID
	// Required: true
	ButtonID *int64 `json:"buttonID"`

	// hash
	// Required: true
	Hash model.Hash `json:"hash"`
}

// Validate validates this press button body
func (o *PressButtonBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateButtonID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateHash(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PressButtonBody) validateButtonID(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"buttonID", "body", o.ButtonID); err != nil {
		return err
	}

	return nil
}

func (o *PressButtonBody) validateHash(formats strfmt.Registry) error {

	if err := o.Hash.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "hash")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PressButtonBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PressButtonBody) UnmarshalBinary(b []byte) error {
	var res PressButtonBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
