// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProgramPauseParams creates a new ProgramPauseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProgramPauseParams() *ProgramPauseParams {
	return &ProgramPauseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProgramPauseParamsWithTimeout creates a new ProgramPauseParams object
// with the ability to set a timeout on a request.
func NewProgramPauseParamsWithTimeout(timeout time.Duration) *ProgramPauseParams {
	return &ProgramPauseParams{
		timeout: timeout,
	}
}

// NewProgramPauseParamsWithContext creates a new ProgramPauseParams object
// with the ability to set a context for a request.
func NewProgramPauseParamsWithContext(ctx context.Context) *ProgramPauseParams {
	return &ProgramPauseParams{
		Context: ctx,
	}
}

// NewProgramPauseParamsWithHTTPClient creates a new ProgramPauseParams object
// with the ability to set a custom HTTPClient for a request.
func NewProgramPauseParamsWithHTTPClient(client *http.Client) *ProgramPauseParams {
	return &ProgramPauseParams{
		HTTPClient: client,
	}
}

/*
ProgramPauseParams contains all the parameters to send to the API endpoint

	for the program pause operation.

	Typically these are written to a http.Request.
*/
type ProgramPauseParams struct {

	// Args.
	Args ProgramPauseBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the program pause params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProgramPauseParams) WithDefaults() *ProgramPauseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the program pause params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProgramPauseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the program pause params
func (o *ProgramPauseParams) WithTimeout(timeout time.Duration) *ProgramPauseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the program pause params
func (o *ProgramPauseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the program pause params
func (o *ProgramPauseParams) WithContext(ctx context.Context) *ProgramPauseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the program pause params
func (o *ProgramPauseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the program pause params
func (o *ProgramPauseParams) WithHTTPClient(client *http.Client) *ProgramPauseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the program pause params
func (o *ProgramPauseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the program pause params
func (o *ProgramPauseParams) WithArgs(args ProgramPauseBody) *ProgramPauseParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the program pause params
func (o *ProgramPauseParams) SetArgs(args ProgramPauseBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *ProgramPauseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
