// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/DiaElectronics/lea-central-wash/storageapi/model"
)

// RunDespenserReader is a Reader for the RunDespenser structure.
type RunDespenserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RunDespenserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRunDespenserNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRunDespenserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRunDespenserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRunDespenserNoContent creates a RunDespenserNoContent with default headers values
func NewRunDespenserNoContent() *RunDespenserNoContent {
	return &RunDespenserNoContent{}
}

/* RunDespenserNoContent describes a response with status code 204, with default header values.

OK
*/
type RunDespenserNoContent struct {
}

// IsSuccess returns true when this run despenser no content response has a 2xx status code
func (o *RunDespenserNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this run despenser no content response has a 3xx status code
func (o *RunDespenserNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this run despenser no content response has a 4xx status code
func (o *RunDespenserNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this run despenser no content response has a 5xx status code
func (o *RunDespenserNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this run despenser no content response a status code equal to that given
func (o *RunDespenserNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *RunDespenserNoContent) Error() string {
	return fmt.Sprintf("[POST /run-despenser][%d] runDespenserNoContent ", 204)
}

func (o *RunDespenserNoContent) String() string {
	return fmt.Sprintf("[POST /run-despenser][%d] runDespenserNoContent ", 204)
}

func (o *RunDespenserNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRunDespenserNotFound creates a RunDespenserNotFound with default headers values
func NewRunDespenserNotFound() *RunDespenserNotFound {
	return &RunDespenserNotFound{}
}

/* RunDespenserNotFound describes a response with status code 404, with default header values.

not found
*/
type RunDespenserNotFound struct {
	Payload string
}

// IsSuccess returns true when this run despenser not found response has a 2xx status code
func (o *RunDespenserNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this run despenser not found response has a 3xx status code
func (o *RunDespenserNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this run despenser not found response has a 4xx status code
func (o *RunDespenserNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this run despenser not found response has a 5xx status code
func (o *RunDespenserNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this run despenser not found response a status code equal to that given
func (o *RunDespenserNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *RunDespenserNotFound) Error() string {
	return fmt.Sprintf("[POST /run-despenser][%d] runDespenserNotFound  %+v", 404, o.Payload)
}

func (o *RunDespenserNotFound) String() string {
	return fmt.Sprintf("[POST /run-despenser][%d] runDespenserNotFound  %+v", 404, o.Payload)
}

func (o *RunDespenserNotFound) GetPayload() string {
	return o.Payload
}

func (o *RunDespenserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunDespenserInternalServerError creates a RunDespenserInternalServerError with default headers values
func NewRunDespenserInternalServerError() *RunDespenserInternalServerError {
	return &RunDespenserInternalServerError{}
}

/* RunDespenserInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type RunDespenserInternalServerError struct {
}

// IsSuccess returns true when this run despenser internal server error response has a 2xx status code
func (o *RunDespenserInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this run despenser internal server error response has a 3xx status code
func (o *RunDespenserInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this run despenser internal server error response has a 4xx status code
func (o *RunDespenserInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this run despenser internal server error response has a 5xx status code
func (o *RunDespenserInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this run despenser internal server error response a status code equal to that given
func (o *RunDespenserInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *RunDespenserInternalServerError) Error() string {
	return fmt.Sprintf("[POST /run-despenser][%d] runDespenserInternalServerError ", 500)
}

func (o *RunDespenserInternalServerError) String() string {
	return fmt.Sprintf("[POST /run-despenser][%d] runDespenserInternalServerError ", 500)
}

func (o *RunDespenserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*RunDespenserBody ArgRunDespenser
swagger:model RunDespenserBody
*/
type RunDespenserBody struct {

	// hash
	// Required: true
	Hash *model.Hash `json:"hash"`

	// volume
	// Required: true
	Volume *int64 `json:"volume"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (o *RunDespenserBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// hash
		// Required: true
		Hash *model.Hash `json:"hash"`

		// volume
		// Required: true
		Volume *int64 `json:"volume"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	o.Hash = props.Hash
	o.Volume = props.Volume
	return nil
}

// Validate validates this run despenser body
func (o *RunDespenserBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateHash(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateVolume(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RunDespenserBody) validateHash(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"hash", "body", o.Hash); err != nil {
		return err
	}

	if err := validate.Required("args"+"."+"hash", "body", o.Hash); err != nil {
		return err
	}

	if o.Hash != nil {
		if err := o.Hash.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("args" + "." + "hash")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("args" + "." + "hash")
			}
			return err
		}
	}

	return nil
}

func (o *RunDespenserBody) validateVolume(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"volume", "body", o.Volume); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this run despenser body based on the context it is used
func (o *RunDespenserBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateHash(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RunDespenserBody) contextValidateHash(ctx context.Context, formats strfmt.Registry) error {

	if o.Hash != nil {
		if err := o.Hash.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("args" + "." + "hash")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("args" + "." + "hash")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RunDespenserBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RunDespenserBody) UnmarshalBinary(b []byte) error {
	var res RunDespenserBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
