// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/DiaElectronics/lea-central-wash/storageapi/model"
)

// RunDispenserReader is a Reader for the RunDispenser structure.
type RunDispenserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RunDispenserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRunDispenserNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRunDispenserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRunDispenserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRunDispenserNoContent creates a RunDispenserNoContent with default headers values
func NewRunDispenserNoContent() *RunDispenserNoContent {
	return &RunDispenserNoContent{}
}

/* RunDispenserNoContent describes a response with status code 204, with default header values.

OK
*/
type RunDispenserNoContent struct {
}

// IsSuccess returns true when this run dispenser no content response has a 2xx status code
func (o *RunDispenserNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this run dispenser no content response has a 3xx status code
func (o *RunDispenserNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this run dispenser no content response has a 4xx status code
func (o *RunDispenserNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this run dispenser no content response has a 5xx status code
func (o *RunDispenserNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this run dispenser no content response a status code equal to that given
func (o *RunDispenserNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *RunDispenserNoContent) Error() string {
	return fmt.Sprintf("[POST /run-dispenser][%d] runDispenserNoContent ", 204)
}

func (o *RunDispenserNoContent) String() string {
	return fmt.Sprintf("[POST /run-dispenser][%d] runDispenserNoContent ", 204)
}

func (o *RunDispenserNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRunDispenserNotFound creates a RunDispenserNotFound with default headers values
func NewRunDispenserNotFound() *RunDispenserNotFound {
	return &RunDispenserNotFound{}
}

/* RunDispenserNotFound describes a response with status code 404, with default header values.

not found
*/
type RunDispenserNotFound struct {
	Payload string
}

// IsSuccess returns true when this run dispenser not found response has a 2xx status code
func (o *RunDispenserNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this run dispenser not found response has a 3xx status code
func (o *RunDispenserNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this run dispenser not found response has a 4xx status code
func (o *RunDispenserNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this run dispenser not found response has a 5xx status code
func (o *RunDispenserNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this run dispenser not found response a status code equal to that given
func (o *RunDispenserNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *RunDispenserNotFound) Error() string {
	return fmt.Sprintf("[POST /run-dispenser][%d] runDispenserNotFound  %+v", 404, o.Payload)
}

func (o *RunDispenserNotFound) String() string {
	return fmt.Sprintf("[POST /run-dispenser][%d] runDispenserNotFound  %+v", 404, o.Payload)
}

func (o *RunDispenserNotFound) GetPayload() string {
	return o.Payload
}

func (o *RunDispenserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunDispenserInternalServerError creates a RunDispenserInternalServerError with default headers values
func NewRunDispenserInternalServerError() *RunDispenserInternalServerError {
	return &RunDispenserInternalServerError{}
}

/* RunDispenserInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type RunDispenserInternalServerError struct {
}

// IsSuccess returns true when this run dispenser internal server error response has a 2xx status code
func (o *RunDispenserInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this run dispenser internal server error response has a 3xx status code
func (o *RunDispenserInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this run dispenser internal server error response has a 4xx status code
func (o *RunDispenserInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this run dispenser internal server error response has a 5xx status code
func (o *RunDispenserInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this run dispenser internal server error response a status code equal to that given
func (o *RunDispenserInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *RunDispenserInternalServerError) Error() string {
	return fmt.Sprintf("[POST /run-dispenser][%d] runDispenserInternalServerError ", 500)
}

func (o *RunDispenserInternalServerError) String() string {
	return fmt.Sprintf("[POST /run-dispenser][%d] runDispenserInternalServerError ", 500)
}

func (o *RunDispenserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*RunDispenserBody ArgRunDispenser
swagger:model RunDispenserBody
*/
type RunDispenserBody struct {

	// hash
	// Required: true
	Hash *model.Hash `json:"hash"`

	// volume
	// Required: true
	Volume *int64 `json:"volume"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (o *RunDispenserBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// hash
		// Required: true
		Hash *model.Hash `json:"hash"`

		// volume
		// Required: true
		Volume *int64 `json:"volume"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	o.Hash = props.Hash
	o.Volume = props.Volume
	return nil
}

// Validate validates this run dispenser body
func (o *RunDispenserBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateHash(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateVolume(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RunDispenserBody) validateHash(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"hash", "body", o.Hash); err != nil {
		return err
	}

	if err := validate.Required("args"+"."+"hash", "body", o.Hash); err != nil {
		return err
	}

	if o.Hash != nil {
		if err := o.Hash.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("args" + "." + "hash")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("args" + "." + "hash")
			}
			return err
		}
	}

	return nil
}

func (o *RunDispenserBody) validateVolume(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"volume", "body", o.Volume); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this run dispenser body based on the context it is used
func (o *RunDispenserBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateHash(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RunDispenserBody) contextValidateHash(ctx context.Context, formats strfmt.Registry) error {

	if o.Hash != nil {
		if err := o.Hash.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("args" + "." + "hash")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("args" + "." + "hash")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RunDispenserBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RunDispenserBody) UnmarshalBinary(b []byte) error {
	var res RunDispenserBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
