// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/DiaElectronics/lea-central-wash/storageapi/model"
)

// RunArduinoReader is a Reader for the RunArduino structure.
type RunArduinoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RunArduinoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRunArduinoNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRunArduinoNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRunArduinoInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRunArduinoNoContent creates a RunArduinoNoContent with default headers values
func NewRunArduinoNoContent() *RunArduinoNoContent {
	return &RunArduinoNoContent{}
}

/* RunArduinoNoContent describes a response with status code 204, with default header values.

OK
*/
type RunArduinoNoContent struct {
}

// IsSuccess returns true when this run arduino no content response has a 2xx status code
func (o *RunArduinoNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this run arduino no content response has a 3xx status code
func (o *RunArduinoNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this run arduino no content response has a 4xx status code
func (o *RunArduinoNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this run arduino no content response has a 5xx status code
func (o *RunArduinoNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this run arduino no content response a status code equal to that given
func (o *RunArduinoNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *RunArduinoNoContent) Error() string {
	return fmt.Sprintf("[POST /run-arduino][%d] runArduinoNoContent ", 204)
}

func (o *RunArduinoNoContent) String() string {
	return fmt.Sprintf("[POST /run-arduino][%d] runArduinoNoContent ", 204)
}

func (o *RunArduinoNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRunArduinoNotFound creates a RunArduinoNotFound with default headers values
func NewRunArduinoNotFound() *RunArduinoNotFound {
	return &RunArduinoNotFound{}
}

/* RunArduinoNotFound describes a response with status code 404, with default header values.

not found
*/
type RunArduinoNotFound struct {
	Payload string
}

// IsSuccess returns true when this run arduino not found response has a 2xx status code
func (o *RunArduinoNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this run arduino not found response has a 3xx status code
func (o *RunArduinoNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this run arduino not found response has a 4xx status code
func (o *RunArduinoNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this run arduino not found response has a 5xx status code
func (o *RunArduinoNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this run arduino not found response a status code equal to that given
func (o *RunArduinoNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *RunArduinoNotFound) Error() string {
	return fmt.Sprintf("[POST /run-arduino][%d] runArduinoNotFound  %+v", 404, o.Payload)
}

func (o *RunArduinoNotFound) String() string {
	return fmt.Sprintf("[POST /run-arduino][%d] runArduinoNotFound  %+v", 404, o.Payload)
}

func (o *RunArduinoNotFound) GetPayload() string {
	return o.Payload
}

func (o *RunArduinoNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunArduinoInternalServerError creates a RunArduinoInternalServerError with default headers values
func NewRunArduinoInternalServerError() *RunArduinoInternalServerError {
	return &RunArduinoInternalServerError{}
}

/* RunArduinoInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type RunArduinoInternalServerError struct {
}

// IsSuccess returns true when this run arduino internal server error response has a 2xx status code
func (o *RunArduinoInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this run arduino internal server error response has a 3xx status code
func (o *RunArduinoInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this run arduino internal server error response has a 4xx status code
func (o *RunArduinoInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this run arduino internal server error response has a 5xx status code
func (o *RunArduinoInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this run arduino internal server error response a status code equal to that given
func (o *RunArduinoInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *RunArduinoInternalServerError) Error() string {
	return fmt.Sprintf("[POST /run-arduino][%d] runArduinoInternalServerError ", 500)
}

func (o *RunArduinoInternalServerError) String() string {
	return fmt.Sprintf("[POST /run-arduino][%d] runArduinoInternalServerError ", 500)
}

func (o *RunArduinoInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*RunArduinoBody ArgRunArduino
swagger:model RunArduinoBody
*/
type RunArduinoBody struct {

	// hash
	// Required: true
	Hash *model.Hash `json:"hash"`

	// volume
	// Required: true
	Volume *int64 `json:"volume"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (o *RunArduinoBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// hash
		// Required: true
		Hash *model.Hash `json:"hash"`

		// volume
		// Required: true
		Volume *int64 `json:"volume"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	o.Hash = props.Hash
	o.Volume = props.Volume
	return nil
}

// Validate validates this run arduino body
func (o *RunArduinoBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateHash(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateVolume(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RunArduinoBody) validateHash(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"hash", "body", o.Hash); err != nil {
		return err
	}

	if err := validate.Required("args"+"."+"hash", "body", o.Hash); err != nil {
		return err
	}

	if o.Hash != nil {
		if err := o.Hash.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("args" + "." + "hash")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("args" + "." + "hash")
			}
			return err
		}
	}

	return nil
}

func (o *RunArduinoBody) validateVolume(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"volume", "body", o.Volume); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this run arduino body based on the context it is used
func (o *RunArduinoBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateHash(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RunArduinoBody) contextValidateHash(ctx context.Context, formats strfmt.Registry) error {

	if o.Hash != nil {
		if err := o.Hash.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("args" + "." + "hash")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("args" + "." + "hash")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RunArduinoBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RunArduinoBody) UnmarshalBinary(b []byte) error {
	var res RunArduinoBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
