// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSaveParams creates a new SaveParams object
// with the default values initialized.
func NewSaveParams() *SaveParams {
	var ()
	return &SaveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSaveParamsWithTimeout creates a new SaveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSaveParamsWithTimeout(timeout time.Duration) *SaveParams {
	var ()
	return &SaveParams{

		timeout: timeout,
	}
}

// NewSaveParamsWithContext creates a new SaveParams object
// with the default values initialized, and the ability to set a context for a request
func NewSaveParamsWithContext(ctx context.Context) *SaveParams {
	var ()
	return &SaveParams{

		Context: ctx,
	}
}

// NewSaveParamsWithHTTPClient creates a new SaveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSaveParamsWithHTTPClient(client *http.Client) *SaveParams {
	var ()
	return &SaveParams{
		HTTPClient: client,
	}
}

/*SaveParams contains all the parameters to send to the API endpoint
for the save operation typically these are written to a http.Request
*/
type SaveParams struct {

	/*Args*/
	Args SaveBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the save params
func (o *SaveParams) WithTimeout(timeout time.Duration) *SaveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the save params
func (o *SaveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the save params
func (o *SaveParams) WithContext(ctx context.Context) *SaveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the save params
func (o *SaveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the save params
func (o *SaveParams) WithHTTPClient(client *http.Client) *SaveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the save params
func (o *SaveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the save params
func (o *SaveParams) WithArgs(args SaveBody) *SaveParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the save params
func (o *SaveParams) SetArgs(args SaveBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *SaveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
