// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SetConfigVarStringReader is a Reader for the SetConfigVarString structure.
type SetConfigVarStringReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetConfigVarStringReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetConfigVarStringOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewSetConfigVarStringNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSetConfigVarStringInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSetConfigVarStringOK creates a SetConfigVarStringOK with default headers values
func NewSetConfigVarStringOK() *SetConfigVarStringOK {
	return &SetConfigVarStringOK{}
}

/* SetConfigVarStringOK describes a response with status code 200, with default header values.

OK
*/
type SetConfigVarStringOK struct {
}

func (o *SetConfigVarStringOK) Error() string {
	return fmt.Sprintf("[POST /set-config-var-string][%d] setConfigVarStringOK ", 200)
}

func (o *SetConfigVarStringOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetConfigVarStringNotFound creates a SetConfigVarStringNotFound with default headers values
func NewSetConfigVarStringNotFound() *SetConfigVarStringNotFound {
	return &SetConfigVarStringNotFound{}
}

/* SetConfigVarStringNotFound describes a response with status code 404, with default header values.

Not found
*/
type SetConfigVarStringNotFound struct {
}

func (o *SetConfigVarStringNotFound) Error() string {
	return fmt.Sprintf("[POST /set-config-var-string][%d] setConfigVarStringNotFound ", 404)
}

func (o *SetConfigVarStringNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetConfigVarStringInternalServerError creates a SetConfigVarStringInternalServerError with default headers values
func NewSetConfigVarStringInternalServerError() *SetConfigVarStringInternalServerError {
	return &SetConfigVarStringInternalServerError{}
}

/* SetConfigVarStringInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type SetConfigVarStringInternalServerError struct {
}

func (o *SetConfigVarStringInternalServerError) Error() string {
	return fmt.Sprintf("[POST /set-config-var-string][%d] setConfigVarStringInternalServerError ", 500)
}

func (o *SetConfigVarStringInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
