// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SetConfigVarIntReader is a Reader for the SetConfigVarInt structure.
type SetConfigVarIntReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetConfigVarIntReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSetConfigVarIntNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewSetConfigVarIntInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSetConfigVarIntNoContent creates a SetConfigVarIntNoContent with default headers values
func NewSetConfigVarIntNoContent() *SetConfigVarIntNoContent {
	return &SetConfigVarIntNoContent{}
}

/* SetConfigVarIntNoContent describes a response with status code 204, with default header values.

OK
*/
type SetConfigVarIntNoContent struct {
}

func (o *SetConfigVarIntNoContent) Error() string {
	return fmt.Sprintf("[POST /set-config-var-int][%d] setConfigVarIntNoContent ", 204)
}

func (o *SetConfigVarIntNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetConfigVarIntInternalServerError creates a SetConfigVarIntInternalServerError with default headers values
func NewSetConfigVarIntInternalServerError() *SetConfigVarIntInternalServerError {
	return &SetConfigVarIntInternalServerError{}
}

/* SetConfigVarIntInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type SetConfigVarIntInternalServerError struct {
}

func (o *SetConfigVarIntInternalServerError) Error() string {
	return fmt.Sprintf("[POST /set-config-var-int][%d] setConfigVarIntInternalServerError ", 500)
}

func (o *SetConfigVarIntInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
