// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStatusCollectionParams creates a new StatusCollectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStatusCollectionParams() *StatusCollectionParams {
	return &StatusCollectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStatusCollectionParamsWithTimeout creates a new StatusCollectionParams object
// with the ability to set a timeout on a request.
func NewStatusCollectionParamsWithTimeout(timeout time.Duration) *StatusCollectionParams {
	return &StatusCollectionParams{
		timeout: timeout,
	}
}

// NewStatusCollectionParamsWithContext creates a new StatusCollectionParams object
// with the ability to set a context for a request.
func NewStatusCollectionParamsWithContext(ctx context.Context) *StatusCollectionParams {
	return &StatusCollectionParams{
		Context: ctx,
	}
}

// NewStatusCollectionParamsWithHTTPClient creates a new StatusCollectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewStatusCollectionParamsWithHTTPClient(client *http.Client) *StatusCollectionParams {
	return &StatusCollectionParams{
		HTTPClient: client,
	}
}

/*
StatusCollectionParams contains all the parameters to send to the API endpoint

	for the status collection operation.

	Typically these are written to a http.Request.
*/
type StatusCollectionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the status collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StatusCollectionParams) WithDefaults() *StatusCollectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the status collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StatusCollectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the status collection params
func (o *StatusCollectionParams) WithTimeout(timeout time.Duration) *StatusCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the status collection params
func (o *StatusCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the status collection params
func (o *StatusCollectionParams) WithContext(ctx context.Context) *StatusCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the status collection params
func (o *StatusCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the status collection params
func (o *StatusCollectionParams) WithHTTPClient(client *http.Client) *StatusCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the status collection params
func (o *StatusCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StatusCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
